In [8]:
import numpy as np

x = np.array([[2,-1,-2,0],[2,3,2,-2]])
b = np.array([-1.5,.5]).reshape(-1,1)
w = np.array([.5,.5,.5,.5]).reshape(2,2)
w2 = np.array([-2.5,3])
b2 = -.5
x,b,w

(array([[ 2, -1, -2,  0],
        [ 2,  3,  2, -2]]),
 array([[-1.5],
        [ 0.5]]),
 array([[0.5, 0.5],
        [0.5, 0.5]]))

In [9]:
z1 = np.dot(w,x) + b
z1

array([[ 0.5, -0.5, -1.5, -2.5],
       [ 2.5,  1.5,  0.5, -0.5]])

In [10]:
a1 = 1/(1+np.e**-z1)
a1

array([[0.62245933, 0.37754067, 0.18242552, 0.07585818],
       [0.92414182, 0.81757448, 0.62245933, 0.37754067]])

In [11]:
z2 = np.dot(w2,a1) + b2
z2

array([0.71627713, 1.00887176, 0.91131418, 0.44297656])

In [12]:
y =  1/(1+np.e**-z2)
y

array([0.67178669, 0.73279929, 0.71326901, 0.60896806])