# Esercizio

x = 2,2

w = [[.5,.5],[.5,.5]] dimensione : 2x2 perchè 2 neuroni x 2 feature

In [1]:
import numpy as np

x = np.array([2,2]).reshape(-1,1)
b = np.array([-1.5,.5]).reshape(-1,1)
w = np.array([.5,.5,.5,.5]).reshape(2,2)
w2 = np.array([-2.5,3])
b2 = -.5
x,b,w

(array([[2],
        [2]]),
 array([[-1.5],
        [ 0.5]]),
 array([[0.5, 0.5],
        [0.5, 0.5]]))

In [2]:
z1 = np.dot(w,x) + b
z1

array([[0.5],
       [2.5]])

In [3]:
a1 = 1/(1+np.e**-z1)
a1

array([[0.62245933],
       [0.92414182]])

In [4]:
z2 = np.dot(w2,a1) + b2
z2

array([0.71627713])

In [5]:
y =  1/(1+np.e**-z2)
y

array([0.67178669])